filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/lib/algorand/node.log # Path for Algorand node logs
    
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.kibana:
  host: "<ip or domain>:5601" # IP address or URL for Kibana host
  
output.logstash:
  hosts: ["<ip or domain>:5044"] # IP Address or URL for Logstash host
  bulk_max_size: 1024

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

