filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/lib/algorand/node.log
    
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.kibana:
  host: "170.187.147.133:5601"
  
output.logstash:
  hosts: ["170.187.147.133:5044"]
  bulk_max_size: 1024

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

